#!/bin/sh
cd ~
filename=$1__dependents
rm ~/$filename
pkg origin `echo "n" | pkg remove $1 | awk '/\t/'| sed "s:^.::1" `|tail -n +2 |tee -a ~/$filename 
#yes|pkg remove $1
#echo "---"
#echo "now sending to synth"
#yes|synth force `cat ~/$filename`
